/*
 *  Public Domain munch implementation
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_LINE_LEN 2048
#define MAX_SYM_LEN  1024

typedef struct SymbolNode {
    char *name;
    struct SymbolNode *next;
} SymbolNode;

static SymbolNode *ctors_head = (SymbolNode*)NULL; /* __sti__ ... */
static SymbolNode *dtors_head = (SymbolNode*)NULL; /* __std__ ... */

void add_symbol(SymbolNode **head, const char *sym) {
    SymbolNode *node = (SymbolNode *)malloc(sizeof(SymbolNode));
    if (!node) {
        fprintf(stderr, "munch: out of memory\n");
        exit(1);
    }
    
    node->name = strdup(sym);
    if (!node->name) {
        fprintf(stderr, "munch: out of memory\n");
        exit(1);
    }
    
    node->next = *head;
    *head = node;
}

int is_ident_char(int c) {
    return isalnum(c) || c == '_' || c == '$';
}

void process_line(char *line) {
    char *p = line;
    char *match = (char*)NULL;
    
    while ((match = strstr(p, "__st")) != NULL) {
        char *sym_start = match;
        
        if (sym_start > line && *(sym_start - 1) == '_') {
            sym_start--;
        }
        
        char type_char = match[4]; /* 'i' or 'd' */
        
        if ((type_char == 'i' || type_char == 'd') &&
            match[5] == '_' && 
            match[6] == '_') {
            
             if (sym_start > line && is_ident_char(*(sym_start - 1))) {
                 /* False positive inside another word, skip forward */
                 p = match + 1;
                 continue;
             }

             /* Extract the full symbol */
             char sym_buf[MAX_SYM_LEN];
             int len = 0;
             char *cursor = match;
             
             while (*cursor && is_ident_char(*cursor) && len < MAX_SYM_LEN - 1) {
                 sym_buf[len++] = *cursor++;
             }
             sym_buf[len] = '\0';
             
             /* Add to appropriate list */
             if (type_char == 'i') {
                 add_symbol(&ctors_head, sym_buf);
             } else {
                 add_symbol(&dtors_head, sym_buf);
             }
             
             /* Found a valid symbol on this line, stop scanning line */
             return;
        }
        
        /* If check failed, advance search */
        p = match + 1;
    }
}

void print_list_decls(SymbolNode *head) {
    SymbolNode *curr;
    for (curr = head; curr; curr = curr->next) {
        printf("int %s();\n", curr->name);
    }
}

void print_list_array(SymbolNode *head) {
    SymbolNode *curr;
    for (curr = head; curr; curr = curr->next) {
        printf("\t%s,\n", curr->name);
    }
}

void free_list(SymbolNode *head) {
    SymbolNode *tmp;
    while (head) {
        tmp = head;
        head = head->next;
        free(tmp->name);
        free(tmp);
    }
}

int find_arg(int argc, char** argv, char* arg)
{
    int found = 0;
    if (argc > 1)
    {
        for (int i = 1; i < argc; i++) if (!strcmp(arg, argv[i])) found = 1;
    }
    
    return found;
}

void print_help(void)
{
    printf("munch 1.4 - generates static destructors and constructors table from stdin\n");
    printf("\nusage: nm libC.a 1.o | munch > table.m.c\n");
}

int main(int argc, char **argv) {
    if (find_arg(argc, argv, "--help")) {
        print_help();
	return 0;
    }
    
    int uselib = find_arg(argc, argv, "--gen-rt");

    char buffer[MAX_LINE_LEN];
    printf("/* Generated by munch 1.4 */\n\n");
    
    while (fgets(buffer, sizeof(buffer), stdin)) {
        char *nl = strchr(buffer, '\n');
        if (nl) *nl = '\0';
        
        process_line(buffer);
    }

    printf("typedef int (*PFV)();\n"); /* Function pointer type */
    print_list_decls(ctors_head);
    printf("extern PFV _ctors[];\n");
    printf("PFV _ctors[] = {\n");
    print_list_array(ctors_head);
    printf("\t0\n};\n\n");
    print_list_decls(dtors_head);
    printf("extern PFV _dtors[];\n");
    printf("PFV _dtors[] = {\n");
    print_list_array(dtors_head);
    printf("\t0\n};\n");

    free_list(ctors_head);
    free_list(dtors_head);

    return 0;
}
